In [ ]:
import json
import pandas as pd

In [ ]:
def process_responses(responses):
  videos = {}
  for response in responses:
    for video in response['data']:
      if video['type'] == 4:
        continue
      try:
        id = video['item']['id']
        likes = video['item']['stats']['diggCount']
        comments = video['item']['stats']['commentCount']
        views = video['item']['stats']['playCount']
        shares = video['item']['stats']['shareCount']
        desc = video['item']['desc']
        author = video['item']['author']['uniqueId']
        url = f"https://www.tiktok.com/@{author}/video/{id}"

        videos[id] = {
            'likes': likes,
            'comments': comments,
            'views': views,
            'shares': shares,
            'desc': desc,
            'url': url,
        }
      except KeyError:
        print(video)

  return pd.DataFrame(videos)

In [ ]:
responses = []

for i in range(10):
  r= input(f"{i+1}: Enter response: ")
  r.replace('true', 'True')
  r.replace('false', 'False')
  r = json.loads(r)
  responses.append(r)

In [ ]:
df = process_responses(responses)
df = df.T

In [ ]:
csv = df.iloc[0:100].reset_index().rename(columns={'index': "video_id", 'desc': 'caption'})
csv

,video_id,likes,comments,views,shares,caption,url
0,7148170658038648110,11900,304,240900,199,"5 Whiskeys for beginners, #bourbon #kentucky #...",https://www.tiktok.com/@thirstywhale__/video/7...
1,7197249256887979310,15700,434,632400,871,5 overlooked bottles of whiskey! I need to sto...,https://www.tiktok.com/@thewhiskeyfool/video/7...
2,7184063986516708650,50800,437,870000,974,Elemer T Lee Mixes His Bourbon With What? #elm...,https://www.tiktok.com/@brewzle/video/71840639...
3,7195999959672458538,13800,1290,427900,288,Replying to @therryfatazz Discover the top 4 m...,https://www.tiktok.com/@drinkwithwayne/video/7...
4,7200009779899551018,7147,286,247100,273,5 Awesome Whiskeys to Gift! #bourbon #whiskey ...,https://www.tiktok.com/@thewhiskeyfool/video/7...
...,...,...,...,...,...,...,...
95,7195326621702688043,81100,421,850700,2665,Help,https://www.tiktok.com/@kisserkel/video/719532...
96,7200763774624615722,4367,276,133000,314,Start your Bourbon Collection with $225! Here ...,https://www.tiktok.com/@bourbonoftheweek/video...
97,7211201178917424389,35900,197,399900,754,The origin of the tradition of raising a glass...,https://www.tiktok.com/@teelingwhiskey/video/7...
98,7195773210246450478,243100,2597,2900000,1151,Every single time we use the decanter the forb...,https://www.tiktok.com/@maddieames/video/71957...
99,7177840501964492075,92800,495,3300000,2970,Whiskey business #drinktok #cocktailrecipe #wh...,https://www.tiktok.com/@moodycocktails/video/7...

In [ ]:
def get_hashtags(df):
  d = df['caption']
  l = r = 0

  hashtags = []

  while l < len(d):
    if d[l] == "#":
      r = l+1
      while r < len(d) and d[r] != " " and d[r] != "#":
        r += 1

      hashtag = d[l:r]
      hashtags.append(hashtag)
      l = r-1

    l += 1

  return hashtags

In [ ]:
csv['hashtags_in_caption']  = csv.apply(get_hashtags, axis=1)

In [ ]:
csv.to_excel('whiskey.xlsx', index=False)